version: "3.8"
x-othentic-cli: &othentic-cli
  env_file:
    - path: .env
      required: true
  build:
    context: .
    dockerfile: ./Dockerfile

services:
  attester:
    <<: *othentic-cli
    env_file:
      - .env
    command:
      [
        "node",
        "attester",
        "/ip4/10.8.0.69/tcp/9877/p2p/${OTHENTIC_BOOTSTRAP_ID}",
        "--avs-webapi",
        "http://10.8.0.42",
        "--l1-chain",
        "holesky",
        "--l2-chain",
        "base-sepolia",
      ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER}
      - TASK_PERFORMER=0x0000000000000000000000000000000000000000
    networks:
      runallservicesforzscore_p2p:
        ipv4_address: 10.8.0.3

  avs-webapi:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    env_file:
      - .env
    networks:
      runallservicesforzscore_p2p:
        ipv4_address: 10.8.0.42

networks:
  runallservicesforzscore_p2p:
    external: true
    name: runallservicesforzscore_p2p
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1
