x-othentic-cli: &othentic-cli
  env_file:
    - path: .env
      required: true
  build:
    context: .
    dockerfile: ./Dockerfile

services:
  attester:
    <<: *othentic-cli
    env_file:
      - .env
    command:
      [
        "node",
        "attester",
        "/ip4/${OTHENTIC_CLIENT_RPC_ADDRESS}/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
        "--avs-webapi",
        "http://10.8.0.42",
        "--l1-chain",
        "${L1:-mainnet}",
        "--l2-chain",
        "${L2:-base}",
      ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER}
      - TASK_PERFORMER=0x0000000000000000000000000000000000000000
    networks:
      p2p:
        ipv4_address: 10.8.0.2

  avs-webapi:
    build:
      context: .
      dockerfile: ./Dockerfile.att
    env_file:
      - .env
    networks:
      p2p:
        ipv4_address: 10.8.0.42

networks:
  p2p:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
